### PR TITLE
no vold.fstab in 4.4

### PR DESCRIPTION
**Pull request by Agontuk**

### CODE REVIEW

**Comment by 95A31** [comment]
Waiting for confirmation, I am not expert in this field xD

**Comment by Agontuk** [comment]
OK :). vold.fstab was removed from 4.3 since fstab is now unified

**Comment by Agontuk** [comment]
@DevSwift , can you verify and merge it ?

**Comment by DevSwift** [comment]
I can't. 95A31 can do it:)

**Comment by 95A31** [comment]
Tell me that is ok and I merge it :)

**Comment by percy-g2** [comment]
Yes vold is unified . commit is fine

**Comment by 95A31** [comment]
Ok, @Agontuk I can not merge anymore this commit because kumquat.mk is changed. Pusll new commit :)

**Pull request closed without merging**
